# Configuration options https://w3c.github.io/spec-prod/
name: Node CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  validate-and-publish:
    name: Validate and Publish
    runs-on: ubuntu-latest # only linux supported at present
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          VALIDATE_LINKS: true
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: "https://www.w3.org/2019/did-wg/Meetings/Minutes/2019-11-19-did#resolution1"
          W3C_NOTIFICATIONS_CC: "${{ secrets.CC }}"
          W3C_BUILD_OVERRIDE: |
            specStatus: WG-NOTE
            shortname: did-use-cases
